name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Install system librarys
        run: |
          sudo apt install -y libharfbuzz-dev libfribidi-dev
          sudo apt install -y libfontconfig1-dev
          sudo apt install -y libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
          pip install .[test]
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --exclude tests/ --count --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --exclude tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Type check with mypy
        run: |
          mypy mrbios/
      - name: Test with pytest
        run: |
          pytest -s --cov=./mrbios/ tests/ --cov-report=xml
      - name: Upload to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
